kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .SpokeRolebindingName }}-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .SpokeRolebindingName }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ .AgentServiceAccountName }}
    namespace: {{ .AddonInstallNamespace }}
